matrix:
  CI_SCALA_VERSION:
    - 2.12.6
  RUN_SCRIPTED:
    - ./bin/run-ci-scripted.sh
    - ./bin/run-ci-scripted-to-jar.sh

clone:
  git:
    image: plugins/git
    tags: true
    recursive: true
    depth: 50

pipeline:
  restore_cache:
    image: appleboy/drone-sftp-cache
    when:
      ref: [ refs/heads/1.x-bloop, refs/tags/*, refs/pull/*/head ]
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

  tests:
    image: scalacenter/scala-docs:1.3
    when:
      ref: [ refs/heads/1.x-bloop, refs/tags/*, refs/pull/*/head ]
    commands:
      - export DRONE_DIR="/drone"
      - git fetch --tags && git log | head -n 20
      - ./bin/run-ci.sh
      - ${RUN_SCRIPTED}

  publish:
    image: scalacenter/scala-docs:1.3
    secrets: [ sonatype_user, sonatype_password, pgp_password, bintray_user, bintray_pass ]
    volumes:
      - /scalacenter:/keys
    when:
      ref: [ refs/heads/1.x-bloop, refs/tags/* ]
      event: [ push, tag, deployment ]
      status: success
      matrix:
        # Only publish in one of the two different runs of the CI
        CI_SCALA_VERSION: 2.12.6
    commands:
      - git log | head -n 20
      - export DRONE_DIR="/drone"
      - /usr/local/bin/setup_keys.sh
      - /usr/local/bin/store_credentials.sh
      - git status
      - ./bin/sbt-ci.sh \
          "show version" \
          "set pgpPublicRing in Global := file(\"/drone/.gnupg/pubring.asc\")" \
          "set pgpSecretRing in Global := file(\"/drone/.gnupg/secring.asc\")" \
          "zincRoot/releaseEarly" \
          "sonatypeReleaseAll"

  rebuild_cache:
    image: appleboy/drone-sftp-cache
    when:
      ref: [ refs/heads/1.x-bloop, refs/tags/*, refs/pull/*/head ]
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
